apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dumblogger
  name: dumblogger
spec:
  initContainers:
  - name: check-pod-ready
    image: bitnami/kubectl:1.11
    command: ['get pods -n kube-system']
  containers:
  - env:
    - name: ENV
      value: "qa"
    - name: APP
      value: "dumblogger"
    - name: PRODUCT
      value: "platform"
    image: spagiari/json-dumblogger:latest
    imagePullPolicy: Always
    name: dumblogger
